### ISSUE TITLE
Multiple jobs on one scheduler causing Greenlet failed with KeyError

### ISSUE THREAD

**Issue by piejanssens** [viniciuschiele/flask-apscheduler#4] opened 2015-07-21 21:52 UTC
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 375, in _notify_links
    link(self)
  File "/usr/local/lib/python2.7/site-packages/gevent/threading.py", line 22, in _cleanup
    __threading__._active.pop(id(g))
KeyError: 4476187664
(<function _cleanup at 0x10a7a5848>, <Greenlet at 0x10acd3410>) failed with KeyError
```

I have a main job configured to update the db and the clients with new data `updater_job`.
At a certain moment I start another job `downloader_job` using `scheduler.scheduler.add_job()` to start downloading a number of files (separate job so that this is ran in background and independently from `updater_job`. I do another `scheduler.scheduler.add_job()` to start a job `stat_updater`which is doing some stuff with the downloader class used in `download_job`.
If I comment out the line where I add the `stat_updater`job my program runs fine, with it I receive the error mentioned above.

updater_job: interval 5s
downloader_job: trigger=None, next_run_time=datetime.datetime.now() (I just need to run this once)
stat_updater: interval 1s

**Comment by viniciuschiele** [comment] 2015-07-22 09:24
It is not clear at what time you are adding the other jobs, if you could send me a small example to reproduce this issue it would be better.

But even so, this issue seems to be related to APScheduler library, you should open an issue in their bitbucket page.
https://bitbucket.org/agronholm/apscheduler

Cheers!

**Comment by piejanssens** [comment] 2015-07-23 06:53
Has to be because the use of https://pypi.python.org/pypi/pySmartDL/ in my downloader_job job.
Although I'm creating a pySmartDL downloader object with blocking=true, it's still creating multiprocessing pools to download concurrently with multiple connections, which is a must for my application. I have to find some way to cope with that (gevent monkey patching doesn't do the trick).

**Comment by viniciuschiele** [comment] 2015-09-09 16:03
@piejanssens 

Did you find some way to solve this issue?

**Comment by piejanssens** [comment] 2015-09-10 08:01
No unfortunately not. You can have a peek in my code if you want. https://github.com/piejanssens/premiumizer

**Comment by viniciuschiele** [comment] 2016-01-28 10:29
I will close it for now, this issue doesn't seem to be related to flask-apscheduler.

**Closed by viniciuschiele** 2016-01-28 10:29 UTC
