### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by alexonab** [viniciuschiele/flask-apscheduler#12] opened 2016-01-22 14:38 UTC
The scheduled task completes but this error is logged.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/job.py", line 248, in __str__
    return repr_escape(self.__unicode__())
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/job.py", line 252, in __unicode__
    status = 'next run at: ' + datetime_repr(self.next_run_time) if self.next_run_time else 'paused'
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/util.py", line 187, in datetime_repr
    return dateval.strftime('%Y-%m-%d %H:%M:%S %Z') if dateval else 'None'
  File "/usr/local/lib/python2.7/dist-packages/dateutil/tz.py", line 41, in inner_func
    return myfunc(*args, **kwargs).encode()
AttributeError: 'NoneType' object has no attribute 'encode'
Logged from file base.py, line 121
```

**Comment by viniciuschiele** [comment] 2016-01-25 15:18
@alexonab Could you show me how did you have produce this issue?

**Comment by viniciuschiele** [comment] 2016-02-16 13:22
I was not able to reproduce this error, I will close it for now.

**Closed by viniciuschiele** 2016-02-16 13:22 UTC
