### ISSUE TITLE
call scheduler API got error message

### ISSUE THREAD

**Issue by jiangr3** [viniciuschiele/flask-apscheduler#75] opened 2018-05-18 07:50 UTC
Has set SCHEDULER_API_ENABLED = True ,  and try to add job to run only once by scheduler API,  but got error message, what does it mean?
data =  {
"args": ["a test", "select * from table1", "update"], 
"id": "a test", 
"func": "dashboard:job"
}

POST to '/scheduler/jobs' this endpoint.

{
    "error_message": "Item in ``from list'' not a string"
}

**Comment by viniciuschiele** [comment] 2018-05-18 08:52
I've just run it here and it worked.

What looks like your function?

**Comment by jiangr3** [comment] 2018-05-18 11:07
Here is function to add job by sending post request for scheduler API .

def add_job(name, interval, sql, ops='update'):
    # send a post request to add job
    endpoint = current_app.config['ENDPOINT']
    path = API_FOR_SCHEDULER['add_job']['path']
    url = '{0}{1}'.format(endpoint, path)
    logger.info('Will add job of rule %s by endpoint: %s' % (name, url))
    logger.info('Add job detail:\nJob name: %s\nInterval: %s\nSQL: %s' % (name, interval, sql))
    if interval == 0:
        job = {
            'func': 'dashboard:job',
            'args': [name, sql, ops],
            'id': name,
        }
        logger.info('One time job: %s will run.' % name)
        logger.info(json.loads(json.dumps(job, default=util.ComplexEncoder)))
        return requests.session().request(
            API_FOR_SCHEDULER['add_job']['method'],
            url,
            data=json.dumps(job, cls=util.ComplexEncoder),
        )
    else:

        job = {
            'func': 'dashboard:job',
            'trigger': 'interval',
            'next_run_time': datetime.datetime.now(),
            'hours': int(str(interval)),
            'args': [name, sql, ops],
            'id': name,
            'replace_existing': True,
            'timezone': utc
        }
        logger.info(json.loads(json.dumps(job, default=util.ComplexEncoder)))
        logger.info('Repeat job: %s will run.' % name)
        return requests.session().request(
            API_FOR_SCHEDULER['add_job']['method'],
            url,
            data=json.dumps(job, cls=util.ComplexEncoder),
        )


And util.py here:
class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        else:
            return json.JSONEncoder.default(self, obj)

And function job is like as below, so the args value is a list of [name, sql, ops] as above.

def job(name, sql, ops):
    """
    To do the job defined by at database
    :param name: job id
    :param sql:  job sql
    :param ops:  update or init
    :return: no
    """
    if ops == 'init':
        engine.execute(text(sql).execution_options(autocommit=True))
    elif ops == 'update':
         """
         Do others
         """
         pass

In addition,   I use postman to do the post , got the same error.    Does the error relate with system encoding?

**Comment by viniciuschiele** [comment] 2018-05-18 19:29
I can't replicate the issue, I tried with Python 2 and 3.

I ran the example jobs.py and posted this:
```
curl -X POST \
  http://127.0.0.1:5000/scheduler/jobs \
  -d '{
	"id": "test",
        "func": "jobs:job1",
        "args": ["a", "b"]
}'
```
Response:
```json
{
  "id": "test", 
  "name": "test", 
  "func": "jobs:job1", 
  "args": [
    "a", 
    "b"
  ], 
  "kwargs": {}, 
  "trigger": "date", 
  "run_date": "2018-05-18T20:25:39.621034+01:00", 
  "misfire_grace_time": 1, 
  "max_instances": 1, 
  "next_run_time": "2018-05-18T20:25:39.621034+01:00"
}
```

Can you try the example jobs.py ?

**Comment by jiangr3** [comment] 2018-05-19 07:39
Yes, I can run jobs.py without any error. But it's the default wsgi of flask, I'm using gunicorn as web server.  Don't know if any difference caused it.

**Comment by viniciuschiele** [comment] 2018-05-19 15:47
I tried with gunicorn and it also works fine on both PY2 and PY3

I ran gunicorn like this:
```
gunicorn jobs:application
```

If you could debug and find out the stack trace of the error would be great.

**Comment by viniciuschiele** [comment] 2018-05-20 18:57
Interesting, that works for me

```python
obj = __import__(u'jobs', fromlist=[u'job1'])
```

What is the Python version you are using?

Thanks for digging into it

**Comment by jiangr3** [comment] 2018-05-21 01:47
Py2.7.X ,  I tried 2.7.5/2.7.10/2.7.14,  got the same error.

**Comment by viniciuschiele** [comment] 2018-05-21 09:04
Hi,

I wasn't able to find the cause for that error but googling it I found that the common solution for that is to convert the module name to str().

I've pushed a fix around that, it will convert the func name to str for Py2 only.

Can you pull from master and give it a try, please?

**Comment by jiangr3** [comment] 2018-05-22 05:18
Already pull, and works fine now.  Thanks.

**Closed** 2019-03-13 10:24 UTC
Labels: question
